services:
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres_dev_ag
    restart: always
    shm_size: 256mb
    env_file:
      - .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prisma_network

  server_dev:
    image: node:24-alpine
    container_name: server_dev_ag
    restart: always
    working_dir: /usr/src/app/src
    volumes:
      - ./src:/usr/src/app/src
    command: sh -c "npm install && sleep 10 && npm run db:dev && npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - prisma_network

networks:
  prisma_network:
    name: prisma_network_dev

volumes:
  postgres_data_dev: