FROM node:24-alpine AS builder

WORKDIR /usr/src/app

# 1. Copiamos solo archivos de dependencias
COPY ./src/package.json ./src/package-lock.json ./
COPY ./src/tsconfig.json ./

# 2. Instalamos dependencias
RUN npm ci

# 3. Copiar resto del codigo
COPY ./src ./

RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"  npx prisma generate

# 4. Compilamos
RUN pwd && ls ./generated -R  && npm run build

# Production stage
FROM node:24-alpine

WORKDIR /usr/src/app

COPY ./src/package.json ./src/package-lock.json ./

RUN npm ci --omit=dev

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/generated ./generated
# COPIAMOS EL SEED Y LA POBLACIÓN (por si aca)
COPY --from=builder /usr/src/app/seed.ts ./seed.ts
COPY --from=builder /usr/src/app/poblation ./poblation

COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/prisma.config.ts ./prisma.config.ts

EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]
