FROM node:24-alpine AS builder

WORKDIR /usr/src/app

COPY ./src/package.json ./src/package-lock.json ./

RUN npm ci

COPY ./src ./

RUN npm run build

# Production stage
FROM node:24-alpine

WORKDIR /usr/src/app

COPY ./src/package.json ./src/package-lock.json ./

RUN npm ci --omit=dev

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/generated ./generated

EXPOSE 3000

CMD ["sh", "-c", "npm run db:deploy && npm run start"]