name: Backend CI (Quality Gate)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Configurar Variables de Entorno
        run: |
          # Creamos el .env en la raíz para Docker
          echo "POSTGRES_USER=testuser" > .env
          echo "POSTGRES_PASSWORD=testpass" >> .env
          echo "POSTGRES_DB=testdb" >> .env
          echo "DATABASE_URL=postgresql://testuser:testpass@localhost:5432/testdb?schema=public" >> .env
          echo "PORT=3000" >> .env
          
          # Copiamos a /src para la App y Prisma
          cp .env src/.env
          
          # Inyectamos en el sistema del Robot
          cat .env >> $GITHUB_ENV

      - name: 3. Levantar Base de Datos (PostgreSQL)
        run: docker compose -f compose_dev.yaml up -d postgres_db
        env:
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: testpass

      - name: 3.5 Esperar a que la BD esté lista
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Esperando a Postgres..."
            sleep 2
          done

      - name: 4. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'src/package-lock.json'

      - name: 5. Instalar dependencias
        working-directory: ./src
        run: |
          # Instalamos ignorando el bloqueo por seguridad
          npm ci --no-audit
          # Ejecutamos el audit pero añadimos "|| true" para que NO falle el CI aunque haya avisos
          npm audit --audit-level=high || echo "Se encontraron vulnerabilidades, revisarlas luego."

      - name: 6. Preparar Prisma
        working-directory: ./src
        run: |
          npx prisma generate
          npx prisma db push --accept-data-loss

      - name: 7. EJECUTAR TESTS
        working-directory: ./src
        run: npm run test

      - name: 8. Intentar Build de Producción
        working-directory: ./src
        run: npm run build