name: Backend CI (Quality Gate)

on:
  push:
    branches: [ main ]
    ignore:
      - '**.md' # Ignoramos cambios .md

  pull_request:
    branches: [ main ]
    ignore:
      - '**.md' # Ignoramos cambios .md

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Crear archivo .env para el CI
        # Prisma y el servidor necesitan variables de entorno. 
        # Creamos unas temporales para que el Robot pueda conectar.
        # Esta es la URL que usará Prisma para conectarse (postgresql://testuser:testpass@localhost:5432/testdb?schema=public)
        run: |
          # 1. Creamos el archivo .env en la RAÍZ (para Docker Compose)
          echo "POSTGRES_USER=testuser" > .env
          echo "POSTGRES_PASSWORD=testpass" >> .env
          echo "POSTGRES_DB=testdb" >> .env
          echo "DATABASE_URL=postgresql://testuser:testpass@localhost:5432/testdb?schema=public" >> .env
          echo "PORT=3000" >> .env
          
          # 2. Copiamos el mismo archivo a /src (para Prisma y la App)
          cp .env src/.env
          
          # 3. También las inyectamos en el sistema (para mayor seguridad)
          cat .env >> $GITHUB_ENV

      - name: 3. Levantar Base de Datos (PostgreSQL)
        # Usamos vuestro compose de desarrollo para tener la BD lista
        run: docker compose -f compose_dev.yaml up -d postgres_db
        env:
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: testpass

      - name: 3.5 Esperar a que la BD esté lista
        run: |
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Esperando a Postgres..."
            sleep 2
          done

      - name: 4. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'src/package-lock.json' # Ajustar si cambia la ubicación

      - name: 5. Instalar dependencias
        run: |
          npm audit fix
          npm install
        working-directory: ./src

      - name: 6. Preparar Prisma (Migraciones)
        # Esto genera el cliente de Prisma y prepara la BD del CI
        run: npx prisma db push
        working-directory: ./src

      - name: 7. EJECUTAR TESTS
        run: |
          # Forzamos a Prisma a generar el cliente y empujar la estructura
          npx prisma generate
          npx prisma db push --accept-data-loss
        working-directory: ./src

      - name: 8. Intentar Build de Producción
        # Verificamos que el código compila para producción sin errores
        run: npm run build
        working-directory: ./src